### ISSUE TITLE
osquery-perf does not work 

### ISSUE THREAD

**Issue by flyfei-cmd** [dactivllc/osquery-perf#1]
@zwass 
I want to use osquery-perf to test fleet's performance, 
I run the osquery-perf  with following command, 
go run agent.go --enroll_secret "enroll_secret_xxx" --host_count 5000 --start_period 5m --query_interval 60s --config_interval 5m --server_url "https://fleet.i.entropage.com"
enroll_secret_xxx here represents the true enroll secret,  But it get the following output:
 json parse distributed read response:%!(EXTRA *json.SyntaxError=invalid character '<' looking for beginning of value)
 do request: Post "https://fleet.i.entropage.com/api/v1/osquery/enroll": dial tcp: lookup fleet.i.entropage.com: no such host

**Comment by dachin11** [comment]
Just a guess here, but maybe try adding :443 a the end of your server_url.  The help output specifically calls out that server_url needs the protocol and port.

URL (with protocol and port of osquery server) (default "https://localhost:8080")

**Comment by flyfei-cmd** [comment]
> Just a guess here, but maybe try adding :443 a the end of your server_url (assuming you are running it on 443). The help output specifically calls out that server_url needs the protocol and port.
> 
> --server_url "https://fleet.i.entropage.com:443"
> 
> URL (with protocol and port of osquery server) (default "https://localhost:8080")

It still report the same error when I am using   --server_url "https://fleet.i.entropage.com:443"

**Comment by dachin11** [comment]
Well, I tried.  I've never used the package myself....but we do plan to use it to stress test our fleet infra.

Maybe @zwass can help us.

**Comment by zwass** [comment]
Let's please follow up in the thread you started on osquery Slack. The most recent suggestion there was to see if you can access that url via `curl`. Please reply in that thread and we can continue debugging.
